### ISSUE TITLE
Aonly script for lineage os 19

### ISSUE THREAD

**Issue by abhinavprateek** [Iceows/huawei-creator#1]
Is it possible to use https://github.com/Iceows/huawei-creator/blob/android-11/run-huawei-aonly.sh for converting android 12 images?

**Comment by abhinavprateek** [comment]
when trying, it fails with error
`+ sed -i s/ro.iorapd.enable=true/ro.iorapd.enable=false/g etc/prop.default
sed: can't read etc/prop.default: No such file or directory`

looking into the mounted folder d, this file is not present in the etc folder

**Comment by wugo2022** [comment]
sudo ./run-huawei-emui9-ab-a14.sh lineage-21.0-20240217-UNOFFICIAL-arm64_bgN.img "lineage-21.0-2024.02.17" "Huawei_P20_lite (ANE-LX1)" "N" "Y"
使用erofs文件系统无法启动

**Comment by wugo2022** [comment]
sudo ./run-huawei-emui9-ab-a14.sh lineage-21.0-20240217-UNOFFICIAL-arm64_bgN.img "lineage-21.0-2024.02.17" "Huawei_P20_lite (ANE-LX1)" "N" "Y"
Unable to start using erofs file system

**Comment by Iceows** [comment]
a-only script is only for android11 and inferior. Only huawei device with EMUI8 device (kernel 4.4) is supported also
You can't use it for android12 or sup

**Comment by Iceows** [comment]
It is impossible to use this script with android12 img. Android12 don't support aonly device
